if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('1.9.3')
  gem 'i18n', '< 0.7'
  gem 'rest-client', '~> 1.6.8'
  gem 'activesupport', '~> 3.2'
else
  gem 'activesupport'
end

gem 'bill_forward', :path => '../'